import { APP_NAME } from '@/config/siteConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from '@/Providers/QueryProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `${APP_NAME}`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-background max-w-sm m-auto border min-h-screen dark:text-secondary`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
