import { APP_NAME } from '@/config/siteConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from '@/Providers/QueryProvider';
import Navbar from '@/components/Navbar';
export const dynamic = 'force-dynamic';
const inter = Inter({ subsets: ['latin'] });
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: `${APP_NAME}`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-background max-w-md m-auto min-h-screen dark:text-secondary`}
      >
        <NextTopLoader />
        <QueryProvider>
          <div className="pb-24">{children}</div>
          <Navbar />
        </QueryProvider>
      </body>
    </html>
  );
}
